### ISSUE TITLE
IabtcfConsentInfoPlugin.sendConsentInfo

### ISSUE THREAD

**Issue by JohannDesobry** [blaugold/iabtcf_consent_info#17]
Do you know why and how to fix?

```
Fatal Exception: java.lang.NullPointerException:
       at com.terwesten.gabriel.iabtcf_consent_info.IabtcfConsentInfoPlugin.sendConsentInfo(IabtcfConsentInfoPlugin.java:18)
       at com.terwesten.gabriel.iabtcf_consent_info.IabtcfConsentInfoPlugin.sharedPreferencesListener$lambda$0(IabtcfConsentInfoPlugin.java:5)
       at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:637)
       at android.app.SharedPreferencesImpl$EditorImpl.lambda$notifyListeners$0$SharedPreferencesImpl$EditorImpl(SharedPreferencesImpl.java:643)
       at android.app.-$$Lambda$SharedPreferencesImpl$EditorImpl$3CAjkhzA131V3V-sLfP2uy0FWZ0.run(:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8057)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
```

**Comment by skiluk** [comment]
We are getting this same crash. Any more info on this and how to fix?

**Comment by NaoKreuzeder** [comment]
We are experiencing the same crash
`          Fatal Exception: java.lang.NullPointerException:
       at com.terwesten.gabriel.iabtcf_consent_info.IabtcfConsentInfoPlugin.sendConsentInfo(IabtcfConsentInfoPlugin.java:18)
       at com.terwesten.gabriel.iabtcf_consent_info.IabtcfConsentInfoPlugin.sharedPreferencesListener$lambda-0(IabtcfConsentInfoPlugin.java:5)
       at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:637)
       at android.app.SharedPreferencesImpl$EditorImpl.lambda$notifyListeners$0(SharedPreferencesImpl.java:643)
       at android.app.SharedPreferencesImpl$EditorImpl.$r8$lambda$TQ_9B5e1x2X557KXM5HWBb4Ihjc()
       at android.app.SharedPreferencesImpl$EditorImpl$$ExternalSyntheticLambda0.run(:4)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:222)
       at android.os.Looper.loop(Looper.java:314)
       at android.app.ActivityThread.main(ActivityThread.java:8671)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)`

Any updates on this?

**Comment by roma7481** [comment]
same here, Are there any updates on this?

**Comment by mikemoore13** [comment]
same crash here

**Comment by PasqualePuzio** [comment]
same here
